#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jul 01 00:35:14 UTC 2025
maven-metadata-FinallyADecent.xml.error=
maven-metadata-FinallyADecent.xml.lastUpdated=1751330114779
maven-metadata-MavenRepo.xml.error=
maven-metadata-MavenRepo.xml.lastUpdated=1751330114783
maven-metadata-maven.xml.error=
maven-metadata-maven.xml.lastUpdated=1751330114781
maven-metadata-maven2.xml.error=
maven-metadata-maven2.xml.lastUpdated=1751330114783
maven-metadata-maven3.xml.error=Could not transfer metadata net.wesjd\:anvilgui\:1.10.5-SNAPSHOT/maven-metadata.xml from/to maven3 (https\://oss.sonatype.org/content/groups/public/)\: status code\: 401, reason phrase\: Unauthorized (401)
maven-metadata-maven3.xml/@default-maven3-https\://oss.sonatype.org/content/groups/public/.lastUpdated=1751330114782
maven-metadata-maven4.xml.error=
maven-metadata-maven4.xml.lastUpdated=1751330114782
maven-metadata-maven5.xml.lastUpdated=1751330114780
maven-metadata-maven6.xml.error=
maven-metadata-maven6.xml.lastUpdated=1751330114781
maven-metadata-maven7.xml.error=
maven-metadata-maven7.xml.lastUpdated=1751330114779
maven-metadata-maven8.xml.error=
maven-metadata-maven8.xml.lastUpdated=1751330114780
maven-metadata-maven9.xml.error=
maven-metadata-maven9.xml.lastUpdated=1751330114771
